FORMAT: 1A
HOST: http://alltheweather.apiblueprint.org/

# All The Weather

All The Weather is a simple API for requesting weather data. Using this API you can retreieve weather information for multiple cities, deailed forcast for a given city, and radar imagery.

This API also exponses endpoints for tracking analytic information.

## Cities Collection [/cities{?search,maximumCitiesReturned,startCityIndex}]

### List Cities [GET]

This endpoint will return all supported cities. Each city will include a basic 5-day forecast.  

By default, this endpoint will return all cities that are supported by the API. Applications may restrict the number of cities returned by specifying the `maximumCitiesReturned` in the request body. Applications may also support paging by specifying the `startCityIndex` in the request body.

+ Parameters
    
    + search: `Dallas` (string, optional) - A search term that will be used to filter the list of cities.
    + maximumCitiesReturned: 10 (number, optional) - The number of cities to be returned by this endpoint. If omitted, all available cities will be returned
    + startCityIndex: 0 (number, optional) - The starting city number for the results. This attribute can be used for pagination. If this number is larger than the total number of cities, no results will be returned.

+ Response 200 (application/json)

    + Attributes
    
        + startIndex: 0 (number)
        + cities: City (array[City])

## City Detail [/cities/{cityID}]

This endpoint will return detailed, 5-day forecast information, along with current humidity and UV index.

### List City Details [GET]

If a given city ID does not exist, the server will return an `HTTP 404` error.

+ Response 200 (application/json)

    + Attributes
    
        + forecast: DayForecast (array[DayForecast]) - An array of five DayForecast objects for the given city

+ Response 404

    + Body
    
            {
                "message": "Unable to find city for ID 999"
            }
            
## Radar Imagry [/radar]

This endpoint will return all radar imagry URLs for a given city ID

### List Radar URLs [GET]

If a given city ID does not exist, the server will return an `HTTP 404` error.

+ Request (application)

    + Attributes
    
        + cityID: 8744 (number) - The identifier for the city
        
    + Body
    
            {
                "cityID": 8744
            }
            
+ Response 200 (application/json)

    + Attributes
    
        + radarURLs (RadarImagry) - An array of five DayForecast objects for the given city

+ Response 404

    + Body
    
            {
                "message": "Unable to find city for ID 999"
            }

## Page View Analytics [/analytics/page]

This endpoint can be used for posting analytic pageview events. A pageview event can be defined as any time a screen becomes the primary interface for the application.

### Post Pageview [POST]

+ Request (applicaiton/json)

    + Attributes
    
        + name: Home (string, required) - The page name
        + city: Dallas (string) - The city that the page is displaying information for. If the user is not viewing a city, this attribute can be omitted or left blank.
        
+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "message": "Unable to post event for given reasons"
            }


# Data Structures

# DayForecast (object)
The details of the forecast for a given city

## Properties
- highTemperature: 85 (number) - The high temperature for the day
- lowTemperature: 65 (number) - The low temperature for the day
- condition: 1 (number) 
    A range of forecast conditions. This value is a zero-based index into an array of six possible conditions. Those conditions are as follows: 
        - 0 = Sunny
        - 1 = Partly Cloudy
        - 2 = Cloudy
        - 3 = Light Rain
        - 4 = Heavy Rain/Thunderstorms
        - 5 = Snow/Sleet

# City (object)
A city that will have weather

## Properties
- cityID: 8744 (number) - The identifier for the city
- name: Dallas (string) - The city name
- displayName: Dallas, TX (string) - The name for display purposes, including state
- todaysForecast: default (DayForecast) - The forecast for today
- backgroundURL: https://wallpapercave.com/wp/2MdtgXO.jpg (string) - A URL for the image to display as the forecast background

# RadarImagry (object)
The URLs to fetch any radar imagry from.
- radarURLs: default (array[string]) - The URLs to fetch radar imagry from. Can by any-sized array.